name: Run scraper

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write
  actions: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.303

    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Checkout thepbone/FirmwareProviderAPI
      uses: actions/checkout@v4
      with:
        repository: ThePBone/FirmwareProviderAPI
        submodules: true
        path: './scraper'
    
    - name: Run scraper
      env:
        OPENSSL_CONF: "scraper/SamsungFumoClient/openssl.custom"
      shell: bash
      run: | 
        dotnet run --project scraper/FirmwareProviderCLI/

    - uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: .

    - name: Cleanup
      run: |
        rm -rf scraper
        rm *.log

    - name: Publish summary changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Add new firmware binaries

        
